create table [dbo].[ClientOk](
[client_id] [int] IDENTITY(1,1) NOT NULL,
[nume] [varchar](30) NOT NULL,
[adresa] [varchar](30) NOT NULL,
[telefon] [varchar](30) NOT NULL
CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[client_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

create table [dbo].[Comanda](
[comanda_id] [int] IDENTITY(1,1) NOT NULL,
[client_id] [int] NOT NULL
CONSTRAINT [PK_Comanda] PRIMARY KEY CLUSTERED 
(
	[comanda_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO